#spring:
  #application:
    #name: api-gateway
  #config:
    #import: "optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8088/"

server:
  port: 8060

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: cover-letter-service
          uri: lb://cover-letter-service
          predicates:
            - Path=/cover-letter/**
    config:
      enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_REGISTRY_HOST:localhost}:${SERVICE_REGISTRY_PORT:8761}/eureka/