package com.example.demo.domain.userprofile.dto;

import com.example.demo.core.generic.AbstractDTO;
import com.example.demo.domain.user.dto.UserDTO;
import java.util.Date;
import java.util.UUID;

public class UserProfileDTO extends AbstractDTO {

    //id generated by AbstractDTO

    private String profilePictureURL;

    private int age;

    private String address;

    private Date birthDate;

    private UserDTO user;

    public UserProfileDTO(){

    }

    public UserProfileDTO(UUID id, String profilePictureURL, int age, String address, Date birthDate, UserDTO user){
        super(id);
        this.profilePictureURL = profilePictureURL;
        this.age = age;
        this.address = address;
        this.birthDate = birthDate;
        this.user = user;
    }

    public String getProfilePictureURL() {
        return profilePictureURL;
    }

    public void setProfilePictureURL(String profilePictureURL) {
        this.profilePictureURL = profilePictureURL;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Date getBirthDate() {
        return birthDate;
    }

    public UserDTO getUser() {
        return user;
    }

    public void setUser(UserDTO user) {
        this.user = user;
    }

    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
}
