name: Measure coverage

on:
  pull_request:
    branches: [ "main" ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            project
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '18'
      - name: Run Coverage
        working-directory: project/Backend
        run: |
          gradle wrapper
          chmod +x gradlew
          ./gradlew testCoverage

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/testCoverage/testCoverage.xml
#            ${{ github.workspace }}/**/build/reports/jacoco/**/debugCoverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 30
          min-coverage-changed-files: 60
